### ISSUE TITLE
Is this working?

### ISSUE THREAD

**Issue by krishnamaurya-96** [sahilgoyal786/cashback-laravel#2]
Is this working?

**Comment by sahilgoyal786** [comment]
at that time, it was, but now, no idea, :)

it was over 9 years ago

**Comment by krishnamaurya-96** [comment]
Ok Thanks.. can you make any website like cashkaro dot com

**Comment by sahilgoyal786** [comment]
Exactly, this was the idea behind this project but the client abandoned it, when it was 99% done.

**Comment by krishnamaurya-96** [comment]
Have you have and project related to cashback

**Comment by krishnamaurya-96** [comment]
Can you update this project on latest laravel version?

**Comment by manojkcoder** [comment]
I can, but who'll bear the cost?

**Comment by sahilgoyal786** [comment]
sure, I can, but who'll bear the cost?

**Comment by krishnamaurya-96** [comment]
What's your offer?
